<#
.SYNOPSIS
    Will return a psobject from XML file generated by EnvironementSettingsGenerator
.DESCRIPTION
    Will return a new psobject of format
    Property name being the settings name (i.e. Column A)
    Property Value is Innertext of generated xml node.
.PARAMETER Xml
    Contents of an XML file passed as xml
.EXAMPLE
    Get-ConfigFromXml -Xml ([xml](Get-Content $pathToXmlFile))
    Explanation of what the example does
.NOTES
    EnvironmentSettingsGenerator is a tool authored by Thomas F. Abraham under MIT license
    Available at  : https://github.com/tfabraham/EnvironmentSettingsManager
    Documentation : http://www.tfabraham.com/BTDFDocs/V5_0/DeploymentFrameworkForBizTalkDocs.html?EnvironmentSettingsExporterEnvir.html
#>
function Get-ConfigFromXml{
    param(
        $Xml
    )

    process{
        foreach ($Setting in @($Xml.settings)) {
            $psobject = New-Object psobject
            foreach($Node in @($Setting.property)){
                $psobject | Add-Member NoteProperty $Node.name $Node.InnerText
            }
            return $psobject
        }
    }
}